services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data:
